import argparse
from climatepixdb.core.database import ClimatePixDatabase


def main():
    parser = argparse.ArgumentParser(
        prog='Helper script to upload images on ClimatePix database',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""
    This script cant be used to remotely upload images in ClimatePix database
    (type --help to display documentation).

    A credentials file named "credentials.json" must be present in the working directory
    to help the script connect to database.

    If you don't have this file, please contact a CCAI project member.

    If you have this file, either place it where you want to run the script,
    or run the script where the file is stored."""
    )
    parser.add_argument('metadata', type=str,
                        help='Path to a JSON file generated by download script '
                             '`climatepixdb.download`. Data in JSON will be used to locate images, '
                             'associate metadata, and create corresponding entries in database.')
    args = parser.parse_args()
    database = ClimatePixDatabase()
    database.upload(args.metadata)

if __name__ == '__main__':
    main()
